### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../TaxiBJ/DMVST_flow/flowioK_TaxiBJ_13_30min_local_in.npy'

### ISSUE THREAD

**Issue by ByskyXie** [deepkashiwa20/DL-Traff-Grid#2]
When running "workTaxiBJ/predflowio/predflowio_STDN_noflow.py", it throws the following sentence:
FileNotFoundError: [Errno 2] No such file or directory: '../../TaxiBJ/DMVST_flow/flowioK_TaxiBJ_13_30min_local_in.npy'

How to acquire these files? PLS

**Comment by ByskyXie** [comment]
OK, I run the "preprocess_flow.py", the question is address, LoL.

**Comment by deepkashiwa20** [comment]
Yes, it is the preprocess_flow.py. Good luck.
